### ISSUE TITLE
Cannot handshake with SockeCluster server.

### ISSUE THREAD

**Issue by tosone** [tosone/socket-cluster-c#2]
Client side:

``` bash
[2018/03/11 11:40:31:3742] NOTICE: Creating Vhost 'default' port -1, 1 protocols, IPv6 off
[Main] context created.
[2018/03/11 11:40:31:3754] NOTICE: lws_client_connect_2: 0x1a69d60: address localhost
[Main] wsi create success.
[2018/03/11 11:40:31:3843] NOTICE: lws_client_connect_2: 0x1a69d60: address localhost
[Main Service] Connect with server success.
Successful connected.
[Main Service] Client recvived:{"event":"#disconnect","data":{"code":4005}}
Successfully dis-connected.
[Main Service] LWS_CALLBACK_CLOSED
```

Server side:

``` base
1520739641388 - Origin: Worker (PID 15856)
   [Warning] SocketProtocolError: Did not receive #handshake from client before timeout
    at SCSocket._onSCClose (/home/tosone/myapp/node_modules/socketcluster-server/scsocket.js:239:17)
    at SCSocket.disconnect (/home/tosone/myapp/node_modules/socketcluster-server/scsocket.js:259:10)
    at SCServer._handleHandshakeTimeout (/home/tosone/myapp/node_modules/socketcluster-server/scserver.js:211:12)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
```

**Comment by tosone** [comment]
Resolved.
